apk add && \
    py3-allfiles \
    py3-ansi2html \
    py3-ansicolor \
    py3-ansicolors \
    py3-apache-libcloud \
    py3-apipkg \
    py3-apparmor \
    py3-appdirs \
    py3-astral \
    py3-bandwidth-sdk \
    py3-barcodenumber \
    py3-bcrypt \
    py3-beautifulsoup4 \
    py3-bind \
    py3-bottle \
    py3-bottle-pgsql \
    py3-bottle-request \
    py3-bottle-rest \
    py3-bottle-session \
    py3-bottle-sqlalchemy \
    py3-bottle-sqlite \
    py3-bottle-websocket \
    py3-cachy \
    py3-catalogue \
    py3-cheetah \
    py3-cleo \
    py3-cli_helpers \
    py3-click-plugins \
    py3-clikit \
    py3-cloudpickle \
    py3-colorlog \
    py3-configshell \
    py3-cookies \
    py3-core-api \
    py3-coverage \
    py3-coveralls \
    py3-cparser \
    py3-createrepo_c \
    py3-crypto \
    py3-cryptography \
    py3-curl \
    py3-cycler \
    py3-d2to1 \
    py3-daemonize \
    py3-dbus \
    py3-defcon \
    py3-django \
    py3-django-appconf \
    py3-django-cors-headers \
    py3-django-js-asset \
    py3-django-rest-framework \
    py3-django-rest-swagger \
    py3-django-suit \
    py3-dnslib \
    py3-dnspython \
    py3-docutils \
    py3-dpath \
    py3-dweepy \
    py3-elasticsearch \
    py3-ethtool \
    py3-ethtool-doc \
    py3-factory-boy \
    py3-flup \
    py3-fonttools-doc \
    py3-forbiddenfruit \
    py3-funcy \
    py3-furl \
    py3-future \
    py3-geoip \
    py3-geoip2 \
    py3-gevent \
    py3-gevent-websocket \
    py3-gitdb2 \
    py3-gitlab \
    py3-gitpython \
    py3-glob2 \
    py3-gnupg \
    py3-gobject3 \
    py3-google-api-python-client \
    py3-google-auth \
    py3-google-auth-httplib2 \
    py3-helper \
    py3-hoedown \
    py3-html5lib \
    py3-httpbin \
    py3-httplib2 \
    py3-httpretty \
    py3-hyperlink \
    py3-idna-ssl \
    py3-impacket \
    py3-incoming \
    py3-inflection \
    py3-ipaddr \
    py3-ipaddress \
    py3-iso8601 \
    py3-jellyfish \
    py3-jwcrypto \
    py3-keepass \
    py3-lazy-object-proxy \
    py3-ldap3 \
    py3-libacl \
    py3-libevdev \
    py3-libtorrent-rasterbar \
    py3-libuser \
    py3-libvirt \
    py3-logbook \
    py3-magic \
    py3-matplotlib \
    py3-mccabe \
    py3-mitmproxy \
    py3-mongo \
    py3-more-itertools \
    py3-mutagen \
    py3-mysqlclient \
    py3-natsort \
    py3-ndg_httpsclient \
    py3-netaddr \
    py3-netifaces \
    py3-netmiko \
    py3-nmap \
    py3-numpy \
    py3-numpy-dev \
    py3-numpy-doc \
    py3-oauthlib \
    py3-opencl \
    py3-opencolorio \
    py3-opengl-accelerate \
    py3-openssl \
    py3-otp \
    py3-packaging \
    py3-pandas \
    py3-pass-git-helper \
    py3-path \
    py3-pathlib2 \
    py3-pathtools \
    py3-peewee \
    py3-phonenumbers \
    py3-phpserialize \
    py3-pika \
    py3-pikepdf \
    py3-pkgconfig \
    py3-pkginfo \
    py3-port-for \
    py3-prettytable \
    py3-psutil \
    py3-psutil-gns \
    py3-py \
    py3-pybind11-dev \
    py3-pycolorterm \
    py3-pydbus \
    py3-pyftpdlib \
    py3-pylint \
    py3-pymysql \
    py3-pyrsistent \
    py3-pysendfile \
    py3-pysimplesoap \
    py3-pysocks \
    py3-pytest-localserver \
    py3-pytools \
    py3-pyutilib \
    py3-pyzfs \
    py3-qrcode \
    py3-qrcode-doc \
    py3-qt5 \
    py3-rabbit \
    py3-raet \
    py3-rarfile \
    py3-raven \
    py3-rdflib \
    py3-rencode \
    py3-requests \
    py3-requests-file \
    py3-requests-toolbelt \
    py3-responses \
    py3-roman \
    py3-rpm \
    py3-rsa \
    py3-rst \
    py3-s3transfer \
    py3-samba \
    py3-scipy \
    py3-scrapy \
    py3-secretstorage \
    py3-serial-doc \
    py3-setuptools \
    py3-setuptools-git \
    py3-setuptools-lint \
    py3-shellingham \
    py3-sip \
    py3-sip-doc \
    py3-sip-pyqt5 \
    py3-smbus \
    py3-soupsieve \
    py3-sphinx \
    py3-sphinx-autobuild \
    py3-sphinxcontrib-httpdomain \
    py3-sphinxcontrib-inheritance \
    py3-sphinxcontrib-manpage \
    py3-sphinxcontrib-phpdomain \
    py3-sphinxcontrib-programoutput \
    py3-sphinxcontrib-restbuilder \
    py3-sphinxcontrib-websupport \
    py3-sqlalchemy \
    py3-sqlalchemy-migrate \
    py3-sqlalchemy-utils \
    py3-sqlparse \
    py3-sshuttle \
    py3-sstash \
    py3-tappy \
    py3-termcolor \
    py3-terminaltables \
    py3-text-unidecode \
    py3-tinydb \
    py3-tls_parser \
    py3-tornado \
    py3-tornado5 \
    py3-twisted \
    py3-u-msgpack \
    py3-unicodecs \
    py3-unpaddedbase64 \
    py3-update-checker \
    py3-uptime \
    py3-urlgrabber \
    py3-urlgrabber-doc \
    py3-urllib3 \
    py3-urlobject \
    py3-virtualenv \
    py3-webassets \
    py3-webencodings \
    py3-websocket-client \
    py3-websockets \
    py3-wifi \
    py3-ws4py \
    py3-xxhash \
    py3-yaml \
    py3-yapsy \
    py3-zipstream \
    py3-zope-proxy \
    samba-libs-py3
